---
# This playbook is intended to be included from playbooks/updates/cloud_provider.yml
- name: Update cloud provider config
  hosts: oo_masters_to_config
  serial: 1
  tasks:
  - import_role:
      name: openshift_cloud_provider
      tasks_from: main.yml

- import_playbook: restart.yml
  vars:
    openshift_rolling_restart_mode: 'services'
